<a href="https://colab.research.google.com/github/TheMetaSetter/practice-coding/blob/master/torchcode/templates/02_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.8 MB/s eta 0:00:00


In [2]:
import torch

In [79]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    x = x - torch.max(x)
    return torch.exp(x) / (torch.exp(x).sum(dim=dim).unsqueeze(dim=dim) + 1e-10)

In [76]:
x = torch.tensor([[1.0, 2.0, 3.0, 4.0],[5.0, 6.0, 7.0, 8.0]])
torch.exp(x).size()

torch.Size([2, 4])

In [74]:
my_softmax(x)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]])

In [47]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]])

In [56]:
torch.exp(x).sum(dim=-1).unsqueeze(dim=-1)

tensor([[  84.7910],
        [4629.4331]])

In [58]:
torch.exp(x) / torch.exp(x).sum(dim=-1).unsqueeze(dim=-1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]])

In [80]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

Output: tensor([0.0900, 0.2447, 0.6652])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [81]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ✅ [1/3] Basic 1-D (0.5ms)
  ✅ [2/3] 2-D along dim=-1 (0.4ms)
  ✅ [3/3] Numerical stability (1.1ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (2.0ms total)
  Progress saved. Run status() to see your dashboard.

